apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: vikyb-ambulance-ufe-content
spec:
  microFrontend: vikyb-ambulance-ufe
  element: vikyb-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?vikyb-ambulance-wl(/.*)?$"