apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: vikyb-ambulance-ufe-content
spec:
  microFrontend: vikyb-ambulance-ufe
  element: vikyb-ambulance-wl-app
  attributes:
    - name: base-path
      value: ./vikyb-ambulance-wl/
    - name: api-base
      value: http://localhost:5001/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?vikyb-ambulance-wl(/.*)?$"